---

- name: Update the cache.........
  apt:
    update_cache: yes


- name: Installing libpam-google-authenticator ...
  apt: name=libpam-google-authenticator state=installed
  

- name: run google authenticator command
  shell: yes  | google-authenticator
  register: prompt
  become_user: vagrant

- debug:
    var: prompt.stdout_lines

- name: Update sshd file
  lineinfile:
    path: /etc/pam.d/sshd
    backup: yes
    line: 'auth required pam_google_authenticator.so'
    insertafter: EOF

- name: Update sshd_config file
  lineinfile:
    path: /etc/ssh/sshd_config
    backup: yes
    regexp: '^ChallengeResponseAuthentication '
    insertafter: '^ChallengeResponseAuthentication '
    line: 'ChallengeResponseAuthentication yes'
  notify: Restart sshd service
